# Welding Video Segmentation Configuration

model:
  path: "models/yolov8n_seg.hef"
  input_size: [640, 640, 3]  # YOLOv8n-seg standard input size
  target_size: [720, 1280]  # Resize for your target resolution
  confidence_threshold: 0.5
  iou_threshold: 0.45
  num_classes: 80  # COCO dataset classes

camera:
  resolution: [720, 1280]   # Height x Width
  framerate: 30
  format: "RGB888"

processing:
  target_fps: 25
  enable_boundary_extraction: true
  visualization: true
  save_output: false
  instance_colors: true  # Use different colors for each instance

display:
  window_name: "Instance Segmentation"
  overlay_alpha: 0.6
  show_confidence: true
  show_class_names: true 